### ISSUE TITLE
clean_commonscat padá

### ISSUE THREAD

**Issue by JAnDud** [matejsuchanek/pywikibot-scripts#8]
PO uvedení nové verze dostávám tuto chybu:
(číslo řádku je několik posunuté, mám přidaná shrnutí)

```
4 pages read
0 pages written
Execution time: 18 seconds
Read operation time: 4 seconds
Script terminated by exception:

ERROR: TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "C:\pwb\pwb.py", line 263, in <module>
    if not main():
  File "C:\pwb\pwb.py", line 257, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "C:\pwb\pwb.py", line 121, in run_python_file
    main_mod.__dict__)
  File ".\scripts\clean_commonscat3.py", line 151, in <module>
    main()
  File ".\scripts\clean_commonscat3.py", line 148, in main
    bot.run()
  File "C:\pwb\pywikibot\bot.py", line 1435, in run
    self.treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1722, in treat
    super(ExistingPageBot, self).treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1786, in treat
    super(NoRedirectPageBot, self).treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1649, in treat
    self.treat_page()
  File ".\scripts\clean_commonscat3.py", line 106, in treat_page
    pywikibot.output('Importing P373 to %s' % (page.title(), item.getID()))
TypeError: not all arguments converted during string formatting
<type 'exceptions.TypeError'>
CRITICAL: Closing network session.
```

**Comment by JAnDud** [comment]
pouštěno na id.wiki, ale padá i na eo nebo en
import na WD se neprovede

**Comment by JAnDud** [comment]
předchozí verze naopak padala po provedeném imporu
```
>>> Langowan <<<
Importing P373 from Langowan to Q20426069
Executing remaining deferred callbacks: 2 left
Page [[Bangsa Filistin]] saved
Page [[Langgur, Kei Kecil, Maluku Tenggara]] saved

8 pages read
1 pages written
Execution time: 9 seconds
Read operation time: 2 seconds
Write operation time: 9 seconds
Script terminated by exception:

ERROR: AttributeError: 'WikidataBot' object has no attribute 'source_values'
Traceback (most recent call last):
  File "C:\pwb\pwb.py", line 263, in <module>
    if not main():
  File "C:\pwb\pwb.py", line 257, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "C:\pwb\pwb.py", line 121, in run_python_file
    main_mod.__dict__)
  File ".\scripts\clean_commonscat1.py", line 139, in <module>
    main()
  File ".\scripts\clean_commonscat1.py", line 136, in main
    bot.run()
  File "C:\pwb\pywikibot\bot.py", line 1435, in run
    self.treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1722, in treat
    super(ExistingPageBot, self).treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1786, in treat
    super(NoRedirectPageBot, self).treat(page)
  File "C:\pwb\pywikibot\bot.py", line 1649, in treat
    self.treat_page()
  File ".\scripts\clean_commonscat1.py", line 98, in treat_page
    ref = self.getSource()
  File "C:\pwb\scripts\myscripts\wikidata.py", line 74, in getSource
    self.source = WikidataBot().getSource(self.site)
  File "C:\pwb\pywikibot\bot.py", line 1904, in getSource
    if (site.family.name in self.source_values and
AttributeError: 'WikidataBot' object has no attribute 'source_values'
<type 'exceptions.AttributeError'>
CRITICAL: Closing network session.`
```

**Comment by matejsuchanek** [comment]
Promiň, já to včera testoval bez ukládání, ale bude nutné pouštět se `-simulate`.

>  (číslo řádku je několik posunuté, mám přidaná shrnutí)

Proč si nechávat upravené verze pro sebe? (Tím myslím, abys třeba ta shrnutí poslal.)

**Comment by JAnDud** [comment]
Mám přidaná shrnutí, ale jen v angličtině, lokalizaci do indonéštiny, javánštiny ani esperanta si netroufnu :-)
